### ISSUE TITLE
Add to organization

### ISSUE THREAD

**Issue by 2maz** [pyspace/pyspace#28]
@MMKrell @HWiese1980 @aseeland @sstraube @jmetzen 
Could anybody add me to this organization for doing maintenance. thx

**Comment by 2maz** [comment]
thx @HWiese1980

**Comment by HWiese1980** [comment]
You're welcome, @2maz 

Hope it was okay that I quickly decided to invite him and give him owner rights, @MMKrell @aseeland @sstraube @jmetzen

**Comment by HWiese1980** [comment]
@2maz while we're at it, there has been a bit going on since the last official release of pySPACE to the public (last commit here was in December 2017) - among it quite a piece of work done by a student regarding migration to Python 3. In my humble opinion before any other maintenance can be done, this should have top priority to be complete and released as any further work on the code here means working with a deprecated Python environment.

**Comment by 2maz** [comment]
@HWiese1980 Thanks for the hint, I actually did some refactoring already - latest state is on refactory_python3 branch. I starting with master and 2to3-2.7 did most of the conversion work for me. Now all unittests except for 3 where I would have to convert binary pass again. 
What I am missing is a proper full test case right now. In case you are aware of a state in the repo where the examples would run fine - that would be much appreciated.

**Comment by HWiese1980** [comment]
In the DFKI internal repository there are a lot of additional unit tests that another one of my former students created. AFAIK there's no end-to-end test that deserves the name. Alas, I don't have any access to the internal repository anymore, thus can't say what has happened around the internal repo since I left the DFKI by the end of October last year. 

I'd love to do some additional work around it, contribute too, whenever I feel like it - now that I don't get paid for it anymore (funny effect, isn't it? It has even been scientifically proven; I can't just find the publication right now). In the first couple months at my new employer I got the opportunity to get to know quite some cool tools to raise overall code quality, among them pre-commit hooks as sort of a meta-toolkit for automated code quality assurance... and stuff like that. I'd love to throw them at pySPACE - if not just for the lulz! That would require the current internal state to be released though.
